### ISSUE TITLE
Issue with audio files loading in IE11.

### ISSUE THREAD

**Issue by th3d0g** [ekelokorpi/panda-engine#187]
Audio files don't seem to load in IE 11 (11.248.16299.0). Tested with OGG, WAV, and M4A.

Audio works as expected in Edge (41.16299.248.0), Chrome (63.0.3239.132) and Firefox (58.0.2).

Panda Framework: v2.3.0.
Panda Editor: v1.3.1
Platform:  Windows 10 (64 bit)

**Comment by ekelokorpi** [comment]
This should be now fixed in latest dev version
